---
- name: Restart service
  service:
    name: nginx
    state: restarted
  listen: Restart nginx
  when:
    - service_default_state | default('started') == 'started'
    - (ansible_facts['os_family'] == 'Debian') or (ansible_facts['os_family'] == 'RedHat')
    - not ansible_check_mode
